version: '3.8'

services:

  laravel:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development  
    env_file:
      - .env.dev
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000" 
    # depends_on:
    #   - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # Opcional, para acceso directo al servidor de desarrollo
    environment:
      - CHOKIDAR_USEPOLLING=true  # Mejora la detección de cambios en volúmenes
    depends_on:
      - laravel

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    volumes:
    - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - laravel


  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    command: --load-only=en,es


  db:
    image: postgres:14
    env_file:
      - .env.dev
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  dbdata: