services:
  - type: web
    name: caddy
    runtime: docker
    dockerfilePath: caddy/Dockerfile
    dockerContext: caddy
    plan: free
    numInstances: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'

  - type: web
    name: laravel
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    numInstances: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: DB_CONNECTION
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_URL
        sync: false

  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    numInstances: 1


  - type: web
    name: libretranslate
    runtime: image
    plan: free
    image:
      url: docker.io/benjag13/libretranslate:preloaded
    numInstances: 1
    



