services:
  - type: web
    runtime: docker
    name: translator-backend
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    numInstances: 1
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_URL
        sync: false

  - type: web
    runtime: docker
    name: translator-frontend
    plan: free
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    numInstances: 1

  - type: web
    runtime: docker
    name: translator-caddy
    plan: free
    dockerfilePath: caddy/Dockerfile
    dockerContext: caddy
    numInstances: 1

  - type: web
    runtime: image
    name: translator-libretranslate
    plan: free
    image:
      url: docker.io/libretranslate/libretranslate:latest
    dockerCommand: --load-only=en,es   # si querés pasar el flag al CMD de la imagen
    numInstances: 1
    